// <auto-generated />
using System;
using CryptoArbitrage.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoArbitrage.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522165904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoArbitrage.Api.Core.Models.Entities.ArbitrageEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvgBuyPrice")
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("AvgSellPrice")
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("BuyExchange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("BuyFeeUsdt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CoinsTraded")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GrossProfit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GrossSpreadPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetProfit")
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("NetProfitPercent")
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("SellExchange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("SellFeeUsdt")
                        .HasColumnType("numeric");

                    b.Property<string>("SettlementMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalFeesUsdt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TradeVolumeUsdt")
                        .HasColumnType("numeric(24,8)");

                    b.HasKey("Id");

                    b.ToTable("spread_history");
                });
#pragma warning restore 612, 618
        }
    }
}
