// <auto-generated />
using System;
using CryptoArbitrage.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoArbitrage.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523233657_AddPaperTrading")]
    partial class AddPaperTrading
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoArbitrage.Api.Core.Models.Entities.ArbitrageEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvgBuyPrice")
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("AvgSellPrice")
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("BuyExchange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("BuyFeeUsdt")
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("CoinsTraded")
                        .HasColumnType("numeric(24,8)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GrossProfit")
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("GrossSpreadPercent")
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("NetProfit")
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("NetProfitPercent")
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("SellExchange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("SellFeeUsdt")
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("SettlementMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalFeesUsdt")
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("TradeVolumeUsdt")
                        .HasColumnType("numeric(24,8)");

                    b.HasKey("Id");

                    b.ToTable("spread_history");
                });

            modelBuilder.Entity("CryptoArbitrage.Api.Core.Models.Entities.TradeExecutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArbitrageEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InvestedUsdt")
                        .HasColumnType("numeric(24,8)");

                    b.Property<decimal>("NetProfitUsdt")
                        .HasColumnType("numeric(24,8)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArbitrageEventId");

                    b.ToTable("trade_executions");
                });

            modelBuilder.Entity("CryptoArbitrage.Api.Core.Models.Entities.VirtualWalletEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(24,8)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("virtual_wallets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Asset = "USDT",
                            Balance = 1000m,
                            UpdatedAtUtc = new DateTime(2026, 5, 23, 23, 36, 57, 532, DateTimeKind.Utc).AddTicks(8281)
                        });
                });

            modelBuilder.Entity("CryptoArbitrage.Api.Core.Models.Entities.TradeExecutionEntity", b =>
                {
                    b.HasOne("CryptoArbitrage.Api.Core.Models.Entities.ArbitrageEventEntity", "ArbitrageEvent")
                        .WithMany()
                        .HasForeignKey("ArbitrageEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArbitrageEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
